### PR TITLE
Final changes for release 0.1.1

### PR DESCRIPTION
**Pull request by pjones**
(Hopefully) last set of changes before release 0.1.1.

@maksbotan Note that I've moved the repo from the sthenauth organization to my personal account.  I plan on closing the sthenauth organization in the near future.

### CODE REVIEW

**Review by maksbotan — APPROVED** [review]
Looks OK! I did not check the nix part though.

**Comment by pjones** [comment]
I verified all of the nix stuff locally.

Thanks for the help @maksbotan!

**Comment by maksbotan** [comment]
Thanks!
Could you please ping me here once you make a Hackage release?

**Comment by pjones** [comment]
@maksbotan The release has been posted on hackage.

**Comment by maksbotan** [comment]
Wonderful, thanks!

**Pull request merged**
