### PR TITLE
Added TlsClientAuth and SelfSignedTlsClientAuth clientauth methods.

### PR DESCRIPTION
**Pull request by ondrap**
This is a simple fix for #3 - just adding these methods works fine with keycloak and is probably much simpler fix than #4

### CODE REVIEW

**Comment by pjones** [comment]
Thanks @ondrap!

I'll have some free time in the next couple of hours and will review this PR.

**Comment by pjones** [comment]
@ondrap Can you explain how this works without needing to change `Credentials` or `applyRequestAuthentication`?  In other words, how does the client supply the TLS certificate to the server?

I'm assuming that this could be done at the TLS layer with the TLS manger, but I'm not certain about that.

**Comment by ondrap** [comment]
The main problem is that the discovery fails (with keycloak, but probably with the others too) when it discovers these values. The field is all the supported auth methods - so as long there are others, it works fine. This really doesn't add 'support' for these methods, just allows the parsing.

**Comment by pjones** [comment]
Okay, if I understand #3, #4, and this issue correctly, the problem is with the discovery response containing client authentication methods that are not supported by this library.  It doesn't seem like anyone needs to be able to use those methods, they just need them listed so the discovery process works correctly.

If that's the case, I prefer my [original suggestion](https://github.com/pjones/openid-connect/issues/3#issuecomment-848221601) so that the discovery document parses correctly, but the type system makes it clear that this library doesn't support those extra client authentication methods.

@ondrap It would be great if you could make that change.  If you don't have time then I might be able to hack something together in the next week or so.

**Comment by ondrap** [comment]
I might be wrong, but it seems to me that these 2 values are generally to be expected in these fields (https://www.rfc-editor.org/rfc/rfc8705) and there is no urgent need to support 'generic' types in this field.

**Comment by pjones** [comment]
I don't find the argument using RFC 8705 very compelling.  That RFC is for OAuth and only has a passing reference to OpenID where it says that these authentication methods could be used there too.

What's most important is that these methods are not listed in any OpenID specification and if we add them to the `ClientAuthentication` then `applyRequestAuthentication` function *should* be changed to support them.  In other words, adding additional constructors to `ClientAuthentication` advertises support for them via the type system and allows someone to construct an invalid object since you can't actually authenticate that way.

I don't want to break the type safety of this library.  That leaves us with two options:

  1. We fully support these authentication methods throughout the code

  2. We add a new type for discovery documents that allows the document to parse but makes it clear that these methods are not actually supported by the library

Option 2 is very simple to implement, but does break backward compatibility.

**Comment by ondrap** [comment]
To be honest I don't quite see the problem.... I understand why would you prefer something like `AuthenticationExtension Text` because more methods could come in the future. However, I don't understand why you would like to have it as a separate type instead of extending the `ClientAuthentication` and thus breaking backwards compatibility?

From the user perspective it is either read from server or, during registration, the user fills that in so that it matches the `Credentials` he is going to use elsewhere in the code. And looking into the `applyRequestAuthentication` code, it would just return `Nothing` if there is no good match between `Credentials` and `[ClientAuthentication]`, but that could easily happen now too regardless. It seems to me there is nothing type-unsafe about this aproach. Maybe I have overlooked something?

It seems to me that the #4 is aiming to support authentication using extensions; that's surely a nice goal, but, honestly, it seems to me that in the real world people are either going for some 'official' extensions, and thus it would be better to get them patch this library and make it available for all, or, they are just going with the auth schemes the library already provides. Currently, everybody who wants to use the library needs to fork it because it immediately fails when doing the discovery.

**Comment by pjones** [comment]
Okay, the more I think about this and dig through the code the more I'm coming around to your way of thinking.

The authorization code flow doesn't directly include `ClientAuthentication` in its type signature.  Instead it uses `Credentials`, which I think is where my confusion was coming from.

So if we update `ClientAuthentication` but leave `Credentials` alone the library isn't actually advertising that it supports TLS certificate authentication.

I'll merge this PR, then update the docs a little bit and release another version.

Thank you for your patience.

**Comment by ondrap** [comment]
Thanks :) Though, do you want to leave it the way I did it or would it be better to have just a 'generic' constructor, something like `UnsupportedAuth Text`? It would probably work better for future-proofing.

**Comment by pjones** [comment]
I do like the idea of having a catch-all constructor but it does make the Aeson instances harder to write.  You'd need to manually write `ToJSON` and `FromJSON` instances.

They both could make use of the generic JSON functions from Aeson and the library's JSON module, except for:

  * On parse failure, fallback to the catch-all constructor

  * When generating JSON, correctly handle the catch-all constructor

**Comment by ondrap** [comment]
I have added the `AuthExtension` constructor and added the `FromJSON`/`ToJSON`. Would this work? Just wondering if `AuthExtension` is a good name, maybe something like `UnsupportedAuthentication`?

**Comment by pjones** [comment]
@ondrap I do like `UnsupportedAuthentication` better.

Last bit of housekeeping: Can you export and use the functions and values from the JSON module instead of duplicating them?  And then please make all of the imports of Aeson fully qualified.  

Thank you for your work on this.

**Comment by ondrap** [comment]
Hopefully done.

**Comment by pjones** [comment]
@ondrap Thank you for this work.  I'll get this released soon.

**Comment by ondrap** [comment]
Thanks, I have some other PRs, do that soon :)

**Pull request merged**
